[package]
name = "miden-core"
version = "0.4.0"
description = "Miden VM core components"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-vm"
categories = ["emulators", "no-std"]
keywords = ["instruction-set", "miden", "program"]
edition = "2021"
rust-version = "1.65"

[lib]
bench = false
doctest = false

[features]
default = ["std"]
std = ["math/std", "winter-utils/std", "winter-crypto/std"]

[dependencies]
math = { package = "winter-math", version = "0.4.2", default-features = false }
crypto = { package = "miden-crypto", version = "0.1.1", default-features = false }
winter-crypto = { package = "winter-crypto", version = "0.4.2", default-features = false }
winter-utils = { package = "winter-utils", version = "0.4.2", default-features = false }
