name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, repoened, synchronize]

jobs:
  check:
    name: Check Rust ${{matrix.toolchain}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Install rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: ${{matrix.toolchain}}
          override: true
      - name: Check
        uses: actions-rs/cargo@v1.0.1
        with:
          command: check
          args: --all-targets

  test:
    name: Test Rust ${{matrix.toolchain}} on ${{matrix.os}} with ${{matrix.args}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
        os: [ubuntu-latest]
        args: [--release, --doc]
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Install rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: ${{matrix.toolchain}}
          override: true
      - name: Test
        uses: actions-rs/cargo@v1.0.1
        env:
          RUSTFLAGS: -C debug-assertions
        with:
          command: test
          args: ${{matrix.args}}

  # we separate the script so the CI will not require the same runner to have
  # both windows and linux capabilities
  test-windows:
    name: Test Rust nightly on windows-2022
    # run windows check only when the target is `main`. will execute for release, push or PR.
    if: github.ref_name == 'main'
    runs-on: windows-2022
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Install rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          override: true
      - name: Test
        uses: actions-rs/cargo@v1.0.1
        env:
          RUSTFLAGS: -C debug-assertions
        with:
          command: test
          args: --release

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Install minimal stable with clippy
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: nightly
          components: clippy
          override: true

      - name: Clippy
        uses: actions-rs/cargo@v1.0.1
        with:
          command: clippy
          args: --all -- -D clippy::all -D warnings

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Install minimal stable with rustfmt
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
          override: true

      - name: rustfmt
        uses: actions-rs/cargo@v1.0.1
        with:
          command: fmt
          args: --all -- --check

  no-std:
    name: no-std
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
        target:
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Install rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: ${{matrix.toolchain}}
          override: true
      - run: rustup target add wasm32-unknown-unknown
      - name: Build
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          args: --verbose --no-default-features --target ${{ matrix.target }}
