name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, repoened, synchronize]

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          components: "clippy, rustfmt"
          override: true
      - uses: actions/setup-python@v4.5.0
      - uses: pre-commit/action@v3.0.0

  test:
    name: Test Rust ${{matrix.toolchain}} on ${{matrix.os}} with ${{matrix.args}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
        os: [ubuntu-latest]
        args: [--release, --doc]
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Install rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: ${{matrix.toolchain}}
          override: true
      - name: Test
        uses: actions-rs/cargo@v1.0.1
        env:
          RUSTFLAGS: -C debug-assertions
        with:
          command: test
          args: ${{matrix.args}}

  # we separate the script so the CI will not require the same runner to have
  # both windows and linux capabilities
  test-windows:
    name: Test Rust nightly on windows-2022
    # run windows check only when the target is `main`. will execute for release, push or PR.
    if: github.ref_name == 'main'
    runs-on: windows-2022
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Install rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          override: true
      - name: Test
        uses: actions-rs/cargo@v1.0.1
        env:
          RUSTFLAGS: -C debug-assertions
        with:
          command: test
          args: --release

  no-std:
    name: no-std
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
        target:
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Install rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: ${{matrix.toolchain}}
          override: true
          target: ${{matrix.target}}
      - name: Build
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          args: --verbose --no-default-features --target ${{matrix.target}}
